# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 20
#  - name: Projects
#    url: '#projects'
#    weight: 30
#  - name: Talks
#    url: '#talks'
#    weight: 30
#  - name: CV
#    url: '#featured'
#    weight: 40
#  - name: File Drawer
#    url: filedrawer/
#    weight: 30 # keep as draft before committing
#  - name: Contact
#    url: '#contact'
#    weight: 70
